### ISSUE TITLE
Error Escaping closure captures non-escaping parameter 'submit'

### ISSUE THREAD

**Issue by ardinh** [paescebu/CustomKeyboardKit#31] opened 2024-11-20 07:41 UTC
hello, i found an error when using alternative direct use, when using function submit handler code error "Escaping closure captures non-escaping parameter 'submit' ". can you help me fix this?

the code is like this
`struct ContentView: View {
    @State var text = "0"
    
    var body: some View {
        TextField("", text: $text)
            .customKeyboard { textDocumentProxy, onSubmit, playFeedback in
                VStack {
                    numberButton(text: "1", uiTextDocumentProxy: textDocumentProxy, playFeedback: playFeedback)
                    numberButton(text: "2", uiTextDocumentProxy: textDocumentProxy, playFeedback: playFeedback)
                    Button("DEL") {
                        textDocumentProxy.deleteBackward()
                        playFeedback?()
                        onSubmit()
                    }
                }
            }
    }
    
    func numberButton(text: String, uiTextDocumentProxy: UITextDocumentProxy, playFeedback: (() -> ())?) -> some View {
        Button(text) {
            uiTextDocumentProxy.insertText(text)
            playFeedback?()
        }
    }
}`

**Comment by paescebu** [comment] 2024-11-20 17:54
Hi @ardinh,

What a great find! That was definitely an oversight from my side!
I pushed a new release just for you so that you are not blocked anymore by that issue!
https://github.com/paescebu/CustomKeyboardKit/releases/tag/1.1.1

Let me know if the issue is resolved, or feel free to close the issue yourself if it's resolved.
Thank you for your support!

Kind regards
Pascal

**Comment by paescebu** [comment] 2024-11-29 05:44
Hey @ardinh 
Did you have any chance to give it a go?

**Comment by paescebu** [comment] 2024-12-12 18:00
Closed due to inactivity

**Closed** 2024-12-12 17:59 UTC
